# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Everest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Everest
  pod 'AFNetworking', '~> 3.0'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  # https://github.com/facebook/facebook-sdk-swift/issues/157
  pod 'FacebookShare', :git => 'https://github.com/1amageek/facebook-sdk-swift'
  pod 'MBProgressHUD'
  pod 'SwiftyJSON'
  pod 'TTTAttributedLabel'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'GoogleSignIn'

end
